### ISSUE TITLE
Publish latest version  1.4.0 to NPM

### ISSUE THREAD

**Issue by mayank23** [reduxjs/redux-mock-store#122]
Hi, can you publish the latest version of redux-mock-store (1.4.0) to NPM?

Thanks!

**Comment by ohtangza** [comment]
@arnaudbenard I think you can help him out easily! :)

**Comment by dmitry-zaets** [comment]
Published

**Comment by vitvad** [comment]
@dmitry-zaets Hi could you please clarify difference in versions ?
here you have 1.2.3 latest, and in npm repo latest is 1.4.0, but you don't have any branch with such tag and master branch files updated last time more than 2 month ago.
it's a bit confusing :confused:

**Comment by dmitry-zaets** [comment]
@vitvad Ah, the current version is 1.4.0, it can be found in the [package.json file](https://github.com/arnaudbenard/redux-mock-store/blob/master/package.json)

I've also added it to the Github Releases
Probably we should add a changelog, but since changes were so minor on each version - it doesn't make much sense.

**Comment by vitvad** [comment]
oh, ok I dind't notice that, just get used that usually tags and npm versions are same.
@dmitry-zaets thx.
