### ISSUE TITLE
Exported external package typings file 'redux-mock-store/index.d.ts' is not a module. Please contact the package author to update the package definition

### ISSUE THREAD

**Issue by brauliodiez** [reduxjs/redux-mock-store#39]
I have downloaded redux-mock-store and it include a definition, when you attempt to use it provides the following error:

Exported external package typings file 'C:/Test/node_modules/redux-mock-store/index.d.ts' is not a module. Please contact the package author to update the package definition

We have implemented a manual typing for redux-mock-store, that worked fine for us:

```
/// <reference path="../../typings/globals/redux/index.d.ts"/>

declare module "redux-mock-store" {
    interface MockStore extends Redux.Store {
        getState(): any;
        getActions(): Array<any>;
        dispatch(action: any): any;
        clearActions(): void;
        subscribe(): any;
    }

    function configureStore(...args: any[]) : (...args: any[]) => MockStore;
    export = configureStore;
}

```

This index.d.ts is providing conflicts (even excluding node_modules folders), in our case we are manually deleting that file whenever we install the package.Could it be a good idea to remove the d.ts from redux-mock-store, review it and an updated on to the typings repository?

**Comment by arnaudbenard** [comment]
. @dylanparry implemented the TypeScript part of redux-mock-store, can you check with him on how to fix it?

I have never used TS in the past.

**Comment by dylanparry** [comment]
Hi. It looks like the API for Redux Mock Store has changed considerably since I wrote the `index.d.ts` file. For now it's probably best to either replace the file with the code that @brauliodiez has included above, or delete the file reference from the `package.json` until it can be updated correctly.

**Comment by kenjiru** [comment]
Same issue here, the typings file is broken.

**Comment by brauliodiez** [comment]
May I make a fork and ask for pull request?

**Comment by arnaudbenard** [comment]
@brauliodiez Feel free to make a PR 👍 
@dylanparry Thank you for the feedback

**Comment by brauliodiez** [comment]
I have given a try and there is something wrong, if I place the file outside node_modules (as a typing) works fine, but inside node_modules I get the same error again, I will take look.

**Comment by asgarddesigns** [comment]
@brauliodiez Did you find out what the problem is there? Facing the same issue.

**Comment by asgarddesigns** [comment]
So after a bit of searching I came across [this](http://stackoverflow.com/questions/34030542/how-to-create-an-external-module-typescript-definition-file-to-include-with-an) which seems to indicate we shouldn't be declaring a top level module for an external definition. 

Bear in mind I'm pretty new to a lot of this so I may be missing something (or many things).

Changing to the following works for me:

``` Typescript
import {Store} from 'redux';

interface MockStore extends Store {
    getState():any;
    getActions():Array<any>;
    dispatch(action:any):any;
    clearActions():void;
    subscribe():any;
}

declare function configureStore(...args:any[]):(...args:any[]) => MockStore;
export = configureStore;
```

i.e. the top level module has been removed and the function is a declare because "'declare' [is] now required for top level non-interface declarations " - [Typescript - Known breaking changes between 0.8 and 0.9](https://typescript.codeplex.com/wikipage?title=Known%20breaking%20changes%20between%200.8%20and%200.9)

Let me know what you think, I can create a PR if it's needed (and this is correct!).

**Comment by brauliodiez** [comment]
You are right, we have checked and you version is working like a charm. @dylanparry , @arnaudbenard should @asgarddesigns raise a Pull Request includin the fix for the breaking change?

**Comment by mfrachet** [comment]
Anybody for this PR ?

**Comment by arnaudbenard** [comment]
Is everyone happy with this change?

**Comment by dylanparry** [comment]
Yes. Seems to work fine, so go with it.

On Wed, Jun 15, 2016 at 2:52 PM +0100, "Arnaud Bénard" notifications@github.com wrote:

Is everyone happy with this change?

**Comment by arnaudbenard** [comment]
Done! Thanks everyone for the contribution 👍
