### ISSUE TITLE
throwing error when using redux-multi

### ISSUE THREAD

**Issue by rnsloan** [reduxjs/redux-mock-store#43]
https://github.com/arnaudbenard/redux-mock-store/pull/40

This commit added: 

```
if (typeof action.type === 'undefined') {
  throw new Error(
    'Actions may not have an undefined "type" property. ' +
    'Have you misspelled a constant?'
  );
}
```

This will throw if you are using arrays that [redux-multi](https://github.com/ashaffer/redux-multi) will handle e.g:

```
[ 
  { type: 'action1',
    payload: { id: '1234' } 
  },
  { type: 'action2',
    payload: { id: '5678' } 
  } 
]
```

**Comment by dmitry-zaets** [comment]
This check is from [redux itself](https://github.com/reactjs/redux/blob/master/src/createStore.js#L150-L162). If it will not work here - then it will not also work with redux.

But it will work and will not give an error, because when you are using redux-multi middleware - it just dispatches each single action from array separately:

``` javascript
function multi ({dispatch}) {
  return next => action =>
    Array.isArray(action)
      ? action.filter(Boolean).map(dispatch)
      : next(action)
}
```

Code from [code of redux-multi](https://github.com/ashaffer/redux-multi/blob/master/src/index.js#L5-L10)
