### ISSUE TITLE
What's the suggested way to test action creators that rely on previous dispatch calls?

### ISSUE THREAD

**Issue by shepmaster** [reduxjs/redux-mock-store#78]
We've an action creator that looks something like this:

```js
export function changeFilter(from, to) {
  return (dispatch, getState) => {
    // Updates the state with the new values and sets a loading flag
    dispatch(changeFilterRequest(from, to));

    // Now I want to use those newly-set values to build a query string
    // However, the stubbed implementation of `dispatch` doesn't use reducers,
    // so `getState` returns the original value!
    const { activeUsers } = getState();
    return doSomeWebRequest(activeUsersParams(activeUsers))
      .then(response => dispatch(changeFilterSuccess(response)))
  };
}
```

Like many asynchronous action creators, we split it up into two actions, one to signal the start of an action and another to signal the end. However, our web request in the middle relies on the values set by the first dispatch.

The [implementation of `dispatch`](https://github.com/arnaudbenard/redux-mock-store/blob/270a9610c0ccfb3f78a01943a02e9ca1f85024d5/src/index.js#L20-L43) is pretty sparse, and in (obvious) hindsight, we never pass the reducers to the mocked store!

Are there any existing patterns for performing these types of tests?

Thanks for a great library; keep up the good work!

**Comment by arnaudbenard** [comment]
This library doesn't pass the reducers, the goal is to test the dispatched actions. Once way to test this is to separate the second part of your action. It's a good pattern to have one action mutate the state once.

**Comment by shepmaster** [comment]
Thank you for the response!

> the goal is to test the dispatched actions.

Right, and the trick is that we've got the one async action that dispatches two synchronous actions, with the second depending on the state set by the first. Our test wishes to assert that the query parameters of the second dispatched action are correct.

> Once way to test this is to separate the second part of your action. It's a good pattern to have one action mutate the state once.

I apologize, but I believe I'm missing some part of what you are saying here. The React side of the application only knows about `changeFilter` — when the filter is changed we want to immediately perform the web request. It seems like a leaky abstraction if we were to split up the action in such a way that the UI had to know to perform two `dispatch`es for a single event (if that's even possible, which I'm not sure about).

On the other hand, we _do_ have two action creators (`changeFilterRequest`, `changeFilterSuccess`) which handle the separate parts of the action and mutate the state appropriately.

If I could convince you to share a bit more of your time with me, I might suggest that some sample pseudocode of how the action creator would be structured could help explain it better to me.

**Comment by arnaudbenard** [comment]
I'm away this week, I will write a complete reply on Sunday.

**Comment by dmitry-zaets** [comment]
In your case, the easiest way will be to mock a state with a value expected by second action creator, and test it in a way that:
- Test reducer, to expect that when `changeFilterRequest` is dispatched, state of reducer will be changed as expected (with this test you ensure that getState will return what you expect);
- `changeFilterRequest` was dispatched with needed payload;
- `doSomeWebRequest` was called with value returned from getState;
- `changeFilterSuccess` was dispatched with a value, resolved in promise;

The best thing is to separate tests for reducers and actions.
That will allow you to mock your state as you want and test actions, decoupled from reducers.
Otherwise, you will create a complex test where actions depend on reducers and, which will look more like integration test, rather than the unit test.

Sure, there are a lot of debates about how to test redux, but that is a way how redux-mock-store is designed.
We are forcing this approach even more in [redux-actions-assertions](https://github.com/redux-things/redux-actions-assertions), so we expect that you are not interacting with real reducers (expect an initial state rendering part)

**Comment by shepmaster** [comment]
Thank you for your feedback!
